### ISSUE TITLE
Feature Request: Make Images in Comment Tooltips Clickable to Open in Editor

### ISSUE THREAD

**Issue by IronTopi** [mgiesen/Image-Comments#2]
I'd like to have an easy way to open the linked image for editing (think drawio/diagrams.net-images within the vs code editor extension) or viewing in a full editor/view panel.

### Use Case:

- This feature would enable developers to more easily navigate to associated image files without having to dig through the directory structure.
- Allows for quick back-and-forth comparison between code and referenced images.
- Minimum amount of friction to update images when the corresponding code is changed.

### Expected Behavior:

- Hovering over a comment with an image link shows the tooltip with the image.
- Clicking on the image (or an associated link) within the tooltip opens the image file within the VS Code editor.

### Current Behavior:

- Hovering over a comment with an image link shows the tooltip with the image.
- No clickable functionality to open the image in the editor.

**Comment by mgiesen** [comment]
Sorry for the late reply. Is the updated version more like it?
