### ISSUE TITLE
Visual Studio 2022 ?

### ISSUE THREAD

**Issue by GearTheWorld** [mgiesen/Image-Comments#4]
Any plan for Visual Studio 2022 ?

**Comment by mgiesen** [comment]
> Any plan for Visual Studio 2022 ?

I would appreciate the development, but do not plan to do that on my own.

**Comment by mgiesen** [comment]
> Any plan for Visual Studio 2022 ?

There is a good plugin for Visual Studio: https://github.com/risadams/Illuminated-comments

**Comment by GearTheWorld** [comment]
@mgiesen Thanx for your suggestion.  You know, for me I would prefer just PASTE and the storage handled by Visual Studio.
