### ISSUE TITLE
Would like to make a suggestion.

### ISSUE THREAD

**Issue by danlern2** [mgiesen/Image-Comments#5]
I think the option to modify some of the settings would be really nice. 
I'd like to be able to change the default view, so that when I hover over an image comment i dont have to drag the bounding box to see the full picture every time.
Id like to be able to change the size of the header, because right now it takes up a lot of space. 
Maybe a few other convenient style options like that. Thank you for your time.

**Comment by mgiesen** [comment]
Hello @danlern2,

To my knowledge, it is not possible to style the Visual Studio tooltip. Therefore, I can't set the default size for it. If you could find a description of how to do that, I would be glad to implement it, though.

Regarding the header, I can probably find a smaller markdown font.

**Comment by danlern2** [comment]
I'm afraid im no expert in any of this, so i wont be able to find what you cant. No worries.
im a big fan of your extension. i even learned recently it works with GIFs, and thats just so cool.
