### ISSUE TITLE
No details issue - Vs Code

### ISSUE THREAD

**Issue by Oculus-Deus** [mgiesen/Image-Comments#8]
I discovered an issue where the details of the extension don't show up after installing the extension
![Screenshot 2024-09-06 184747](https://github.com/user-attachments/assets/0c1ee9f4-b806-4d4c-84c5-2e938d8ae091)

**Comment by mgiesen** [comment]
Thank you for sharing this information. It appears to be a bug in VS Code. The marketplace pulls the README.md from the Microsoft Store and displays it. After restarting VS Code, it should be displayed correctly again.
