### ISSUE TITLE
Does not work in a multi folder view

### ISSUE THREAD

**Issue by Oculus-Deus** [mgiesen/Image-Comments#9]
The extension only works in single folder view, if i open a project that has multiple folders and files it won't work, maybe you could make it work on a multi folder overview too

**Comment by Oculus-Deus** [comment]
Here's a video

https://github.com/user-attachments/assets/44a729da-0f5e-42ac-acc3-3345ebf3d229

**Comment by mgiesen** [comment]
Thank you for submitting. I'll take a look on it soon.

**Comment by Oculus-Deus** [comment]
Thank you very much for the update, it was needed
Keep up the good work, this extension is very useful!
